### ISSUE TITLE
Make this repository a template instead of people needing forking.

### ISSUE THREAD

**Issue by vinibispo** [husky-misc/husky-challenge-template#1]
I think you should create a template repository, I have done this
I'll explain it:
- Go to the page of the repository
![image](https://user-images.githubusercontent.com/48097622/160237758-6176f8a1-a22e-4a48-b274-54af6d4bb460.png)
- Click on the settings
![image](https://user-images.githubusercontent.com/48097622/160237838-aa219c81-2e1a-49d4-a0f1-d610c324aa10.png)
- Click on the checkbox
🍾 We have done this
![image](https://user-images.githubusercontent.com/48097622/160237876-2f7b1b9c-30ec-46df-9423-63c1eb9b1da4.png)

**Comment by serradura** [comment]
Done! Thanks for the suggestion.
